Output assets/demo.gif
Set FontSize 10
Set Width 1800
Set Height 800
Set Theme "Catppuccin Mocha"

Hide
Type "go build -o dist/podcasts-sync ."
Enter
Type "clear"
Enter
Show

Type "./dist/podcasts-sync"
Enter
Sleep 2

Space
Sleep 1
Type "s"
Sleep 8

Right
Sleep 1
Space
Sleep 0.25
Type "d"
Sleep 2
Enter
Sleep 2

Type "f"
Sleep 3
Down
Sleep 0.25
Enter
Sleep 3

Hide
Ctrl+C
Type "rm ./dist/podcasts-sync"
Enter
